### PR TITLE
Feature 207 editable summary

### PR DESCRIPTION
**Pull request by highperformancecoder**
This change is [Reviewable](https://reviewable.io/reviews/highperformancecoder/minsky/379)

### CODE REVIEW

**Review by Rdmkr — COMMENTED** [review]
> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/highperformancecoder/minsky/379)* status: all files reviewed, 1 unresolved discussion (waiting on @highperformancecoder)

___
*[`gui-js/apps/minsky-electron/src/app/managers/WindowManager.ts` line 72 at r1](https://reviewable.io/reviews/highperformancecoder/minsky/379#-NWX-PTI1tY97wCWDdFz:-NWX-PTI1tY97wCWDdG-:b-b948jq) ([raw file](https://github.com/highperformancecoder/minsky/blob/b298a35943a8f2f77b0ec7eb0cd555f75da31dc0/gui-js/apps/minsky-electron/src/app/managers/WindowManager.ts#L72)):*
> ```XML
>                                        });
>     }
>     catch (err) {} // absorb exceptions, which will mostly be due to bad windows 
> ```

shouldn't we at least log this somehow?

**Comment by highperformancecoder** [comment]
On Sun, May 28, 2023 at 03:59:33AM -0700, Rdmkr wrote:
> @Rdmkr commented on this pull request.
> 
>     Reviewed 15 of 15 files at r1, all commit messages.
>     Reviewable status: all files reviewed, 1 unresolved discussion (waiting on
>     @highperformancecoder)
> 
> ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
> 
> gui-js/apps/minsky-electron/src/app/managers/WindowManager.ts line 72 at r1 (
> raw file):
> 
>                                            });
>         }
>         catch (err) {} // absorb exceptions, which will mostly be due to bad windows
> 
> shouldn't we at least log this somehow?

I'm aware of the general prescription that exceptions should at least
be logged even if otherwise ignored, but I don't know that it's all
that useful here. It is not useful to display the "Bad Window"
exception to the user, and the console log is by and large invisible in
production.


-- 

----------------------------------------------------------------------------
Dr Russell Standish                    Phone 0425 253119 (mobile)
Principal, High Performance Coders     ***@***.***
                      http://www.hpcoders.com.au
----------------------------------------------------------------------------

**Comment by Rdmkr** [comment]
I agree we don't have an easy option for making such errors from production visible to us devs... unless we build in "send error report" functionality... but simply logging it to console may help when we reproduce such problems in development.

**Comment by highperformancecoder** [comment]
On Sun, May 28, 2023 at 04:00:11PM -0700, Rdmkr wrote:
> I agree we don't have an easy option for making such errors from production
> visible to us devs... unless we build in "send error report" functionality...
> but simply logging it to console may help when we reproduce such problems in
> development.

Alright- I'll console.log this one.


-- 

----------------------------------------------------------------------------
Dr Russell Standish                    Phone 0425 253119 (mobile)
Principal, High Performance Coders     ***@***.***
                      http://www.hpcoders.com.au
----------------------------------------------------------------------------

**Pull request merged**
