### PR TITLE
Linux: don't build Tk GUI if not necessary

### PR DESCRIPTION
**Pull request by aledomu**
This change is [Reviewable](https://reviewable.io/reviews/highperformancecoder/minsky/367)

### CODE REVIEW

**Comment by highperformancecoder** [comment]
We still need the Tk build for some regression tests, and utility scripts. It is also handy from some debugging cases. I plan to replace Tk completely with a python binding in due course, but it is relatively low priority, so not yet scheduled.

I might also add the export:package step to the main Makefile, so that you don't need to compile the Typescript *every* *single* *time* you run Minsky.

**Comment by aledomu** [comment]
This does not remove the ability to compile the Tk version. It only disables it for the standard compilation procedure.

**Comment by highperformancecoder** [comment]
> This does not remove the ability to compile the Tk version. It only disables it for the standard compilation procedure.

I was aware of that. But the Tk version really doesn't add any build time when building in parallel, as the final linkage step for the node addon takes so long, and it would be annoying to have to turn around and build the Tk version when needed (which is often).

If it helps, we don't need to build the Tk version on either Windows or Mac, so I'm happy if you want to disable the builds on those systems. Windows builds have MXE set to true, and Mac builds have OS set to Darwin.

**Comment by aledomu** [comment]
I chose the last option, with the caveat that explicitly setting `GUI_TK=0` does avoid the compilation of the Tk GUI binary in Linux.

**Comment by highperformancecoder** [comment]
OK - that will work. Although I think the logic might be simpler if you define GUI_TK=1 in the Makefile, then call make with GUI_TK= (ie undefining it) to disable the gui-tk build.

You could do something similar with a GUI_JS flag as well.

**Comment by aledomu** [comment]
`GUI_TK=1` disables the REST service compilation, so it is the same as having `GUI_JS=1`, but without needing a separate parameter. I prefer it this way since it has the nice effect of keeping the same behaviour as until now if no flag is set.

**Pull request merged**
