### PR TITLE
Context menu for the publication tab button, allowing renaming and re…

### PR DESCRIPTION
**Pull request by highperformancecoder**
…moval. For #1689.

- - -
This change is [Reviewable](https://reviewable.io/reviews/highperformancecoder/minsky/407)

### CODE REVIEW

**Review by Rdmkr — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/highperformancecoder/minsky/407)* status: all files reviewed, 1 unresolved discussion (waiting on @highperformancecoder)

___
*[`gui-js/apps/minsky-electron/src/app/managers/CommandsManager.ts` line 1003 at r1](https://reviewable.io/reviews/highperformancecoder/minsky/407#-Nmp2wZjAlWdU1D2ZVHt:-Nmp2wZjAlWdU1D2ZVHu:b-g3m8ql) ([raw file](https://github.com/highperformancecoder/minsky/blob/d2a167f3836b6f16100856faaeeb3afce8aa62e0/gui-js/apps/minsky-electron/src/app/managers/CommandsManager.ts#L1003)):*
> ```XML
>       width: 300,
>     });
>     return new Promise((resolve)=>{
> ```

since this is an async method we are returning a promise of a promise here... Just curious if that is intentional / ideal / necessary

**Review by highperformancecoder — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/highperformancecoder/minsky/407)* status: all files reviewed, 1 unresolved discussion (waiting on @Rdmkr)

___
*[`gui-js/apps/minsky-electron/src/app/managers/CommandsManager.ts` line 1003 at r1](https://reviewable.io/reviews/highperformancecoder/minsky/407#-Nmp2wZjAlWdU1D2ZVHt:-NmpB6Ko0GeeVcMJthjC:bexva2g) ([raw file](https://github.com/highperformancecoder/minsky/blob/d2a167f3836b6f16100856faaeeb3afce8aa62e0/gui-js/apps/minsky-electron/src/app/managers/CommandsManager.ts#L1003)):*
<details><summary><i>Previously, Rdmkr wrote…</i></summary><blockquote>

since this is an async method we are returning a promise of a promise here... Just curious if that is intentional / ideal / necessary
</blockquote></details>

How would you suggest resolving the returned promise when the opened window is closed?

**Review by Rdmkr — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/highperformancecoder/minsky/407)* status: all files reviewed, 1 unresolved discussion (waiting on @highperformancecoder)

___
*[`gui-js/apps/minsky-electron/src/app/managers/CommandsManager.ts` line 1003 at r1](https://reviewable.io/reviews/highperformancecoder/minsky/407#-Nmp2wZjAlWdU1D2ZVHt:-NmpBdW4D3GGyZDk6E5Y:b-20wkvd) ([raw file](https://github.com/highperformancecoder/minsky/blob/d2a167f3836b6f16100856faaeeb3afce8aa62e0/gui-js/apps/minsky-electron/src/app/managers/CommandsManager.ts#L1003)):*
<details><summary><i>Previously, highperformancecoder (Russell Standish) wrote…</i></summary><blockquote>

How would you suggest resolving the returned promise when the opened window is closed?
</blockquote></details>

I think the return new Promise(...) stuff can stay, but the newPubTab() method should probably not be async (because it has no internal awaits) and any code calling it should not await it.

**Review by Rdmkr — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/highperformancecoder/minsky/407)* status: all files reviewed, 1 unresolved discussion (waiting on @highperformancecoder)

___
*[`gui-js/apps/minsky-electron/src/app/managers/CommandsManager.ts` line 1003 at r1](https://reviewable.io/reviews/highperformancecoder/minsky/407#-Nmp2wZjAlWdU1D2ZVHt:-NmpCNf_-zppikhVFiPG:be3cyhz) ([raw file](https://github.com/highperformancecoder/minsky/blob/d2a167f3836b6f16100856faaeeb3afce8aa62e0/gui-js/apps/minsky-electron/src/app/managers/CommandsManager.ts#L1003)):*
<details><summary><i>Previously, Rdmkr wrote…</i></summary><blockquote>

I think the return new Promise(...) stuff can stay, but the newPubTab() method should probably not be async (because it has no internal awaits) and any code calling it should not await it.
</blockquote></details>

Or rather, should not await it twice. Awaiting the returned promise is still an option... Just be aware that if the method is kept async, you'd need to await twice to await the window closing event.

**Comment by highperformancecoder** [comment]
> > _[Reviewable](https://reviewable.io/reviews/highperformancecoder/minsky/407)_ status: all files reviewed, 1 unresolved discussion (waiting on @highperformancecoder)
> 
> _[`gui-js/apps/minsky-electron/src/app/managers/CommandsManager.ts` line 1003 at r1](https://reviewable.io/reviews/highperformancecoder/minsky/407#-Nmp2wZjAlWdU1D2ZVHt:-NmpCNf_-zppikhVFiPG:be3cyhz) ([raw file](https://github.com/highperformancecoder/minsky/blob/d2a167f3836b6f16100856faaeeb3afce8aa62e0/gui-js/apps/minsky-electron/src/app/managers/CommandsManager.ts#L1003)):_
> Previously, Rdmkr wrote…
> 
> Or rather, should not await it twice. Awaiting the returned promise is still an option... Just be aware that if the method is kept async, you'd need to await twice to await the window closing event.

It is not awaited twice now, but does work as expected. You're probably right that the async annotation is unnecessary, though.

**Review by Rdmkr — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/highperformancecoder/minsky/407)* status: all files reviewed, 1 unresolved discussion (waiting on @highperformancecoder)

___
*[`gui-js/apps/minsky-electron/src/app/managers/CommandsManager.ts` line 1003 at r1](https://reviewable.io/reviews/highperformancecoder/minsky/407#-Nmp2wZjAlWdU1D2ZVHt:-NmpVv8l6aN1DewpgPOP:brl70va) ([raw file](https://github.com/highperformancecoder/minsky/blob/d2a167f3836b6f16100856faaeeb3afce8aa62e0/gui-js/apps/minsky-electron/src/app/managers/CommandsManager.ts#L1003)):*
<details><summary><i>Previously, highperformancecoder (Russell Standish) wrote…</i></summary><blockquote>

It is not awaited twice now, but does work as expected. You're probably right that the async annotation is unnecessary, though.
</blockquote></details>

I tested some code in a sandbox and apparently returning a Promise object is a syntactically legitimate way to return a value to an async method in typescript... the following are equivalent:

static async newPubTab() {
        const twlv = await CommandsManager.getTwelve();
        return twlv + 12;
}
static async newPubTab() {
        const twlv = await CommandsManager.getTwelve();
        return new Promise<number>((resolve) => resolve(twlv + 12));
}

So yes, the async tag is just unnecessary, not strictly speaking wrong as I first thought.

**Review by Rdmkr — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/highperformancecoder/minsky/407)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @highperformancecoder)

**Comment by highperformancecoder** [comment]
> > _[Reviewable](https://reviewable.io/reviews/highperformancecoder/minsky/407)_ status: all files reviewed, 1 unresolved discussion (waiting on @highperformancecoder)
> 
> _[`gui-js/apps/minsky-electron/src/app/managers/CommandsManager.ts` line 1003 at r1](https://reviewable.io/reviews/highperformancecoder/minsky/407#-Nmp2wZjAlWdU1D2ZVHt:-NmpVv8l6aN1DewpgPOP:brl70va) ([raw file](https://github.com/highperformancecoder/minsky/blob/d2a167f3836b6f16100856faaeeb3afce8aa62e0/gui-js/apps/minsky-electron/src/app/managers/CommandsManager.ts#L1003)):_
> Previously, highperformancecoder (Russell Standish) wrote…
> 
> I tested some code in a sandbox and apparently returning a Promise object is a syntactically legitimate way to return a value to an async method in typescript... the following are equivalent:
> 
> static async newPubTab() { const twlv = await CommandsManager.getTwelve();         return twlv + 12; } static async newPubTab() { const twlv = await CommandsManager.getTwelve();         return new Promise((resolve) => resolve(twlv + 12)); }
> 
> So yes, the async tag is just unnecessary, not strictly speaking wrong as I first thought.

I will remove the async, and explictly declare the return type as Promise<void> to make it clearer what is going on, although it is just syntactic sugar

**Pull request merged**
