### PR TITLE
very minor change to fix shape of left notch in IO regions of groups

### PR DESCRIPTION
**Pull request by wdednam**
This change is [Reviewable](https://reviewable.io/reviews/highperformancecoder/minsky/203)

### CODE REVIEW

**Comment by highperformancecoder** [comment]
I'm rejecting this PR, because it changes an output slot to look like an input slot.

**Comment by wdednam** [comment]
> I'm rejecting this PR, because it changes an output slot to look like an input slot.

Oh. sorry. I thought they were supposed to look like mirror images of each other.

**Comment by highperformancecoder** [comment]
On Tue, Aug 04, 2020 at 10:47:47PM -0700, Wynand wrote:
>     I'm rejecting this PR, because it changes an output slot to look like an
>     input slot.
> 
> Oh. sorry. I thought they were supposed to look like mirror images of each
> other.
> 

No - one supposed to look like an input variable, and one like an
output variable. That's not to say the current versions are ideal in
that respect :).


-- 

----------------------------------------------------------------------------
Dr Russell Standish                    Phone 0425 253119 (mobile)
Principal, High Performance Coders     hpcoder@hpcoders.com.au
                      http://www.hpcoders.com.au
----------------------------------------------------------------------------

**Comment by wdednam** [comment]
> On Tue, Aug 04, 2020 at 10:47:47PM -0700, Wynand wrote: I'm rejecting this PR, because it changes an output slot to look like an input slot. Oh. sorry. I thought they were supposed to look like mirror images of each other.
> No - one supposed to look like an input variable, and one like an output variable. That's not to say the current versions are ideal in that respect :).
> […](#)
> --
> ---------------------------------------------------------------------------- Dr Russell Standish Phone 0425 253119 (mobile) Principal, High Performance Coders hpcoder@hpcoders.com.au http://www.hpcoders.com.au ----------------------------------------------------------------------------

Okay, I understand now. Thanks.

**Pull request closed without merging**
