### PR TITLE
Ravel 202 ravel popup

### PR DESCRIPTION
**Pull request by highperformancecoder**
This is about creating a popup window for controlling individual Ravels, as outlined in https://sourceforge.net/p/minsky/ravel/202/

- - -
This change is [Reviewable](https://reviewable.io/reviews/highperformancecoder/minsky/322)

### CODE REVIEW

**Review by Rdmkr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/highperformancecoder/minsky/322)* status: 0 of 16 files reviewed, 4 unresolved discussions (waiting on @highperformancecoder)

___
*[`gui-js/libs/ui-components/src/lib/ravel-widget-view/ravel-widget-view.component.scss` line 4 at r1](https://reviewable.io/reviews/highperformancecoder/minsky/322#-NGmBZdt2t37DRDzgzjb:-NGmBZdt2t37DRDzgzjc:b-py3293) ([raw file](https://github.com/highperformancecoder/minsky/blob/888248890eb2c47623df611b7b3e62ae90df1a01/gui-js/libs/ui-components/src/lib/ravel-widget-view/ravel-widget-view.component.scss#L4)):*
> ```SCSS
> 
> .ravel-cairo-canvas {
>   height: calc(100vh);
> ```

I don't think calc(...) does anything here..? that's usually used to calculate a length based on two heterogenous values i.e. calc(100vh - 20px)
___
*[`gui-js/libs/ui-components/src/lib/ravel-widget-view/ravel-widget-view.component.ts` line 45 at r1](https://reviewable.io/reviews/highperformancecoder/minsky/322#-NGmDgvh1nSaOD5-Ds1R:-NGmDgvh1nSaOD5-Ds1S:bhytsnw) ([raw file](https://github.com/highperformancecoder/minsky/blob/888248890eb2c47623df611b7b3e62ae90df1a01/gui-js/libs/ui-components/src/lib/ravel-widget-view/ravel-widget-view.component.ts#L45)):*
> ```XML
>     this.render();
>     this.initEvents();
>     if (isMacOS()) this.yoffs=-20; // why, o why, Mac?
> ```

If I recall correctly, the javascript mouse event has multiple subtly different X and Y values to choose from, which may include one that has a more homogenous value between different operating systems... it can also matter which HTML element you interept the mouse event on...
___
*[`gui-js/libs/ui-components/src/lib/ravel-widget-view/ravel-widget-view.component.ts` line 63 at r1](https://reviewable.io/reviews/highperformancecoder/minsky/322#-NGmCACF2mm9ON5tN4Ac:-NGmCACF2mm9ON5tN4Ad:b-jobt1l) ([raw file](https://github.com/highperformancecoder/minsky/blob/888248890eb2c47623df611b7b3e62ae90df1a01/gui-js/libs/ui-components/src/lib/ravel-widget-view/ravel-widget-view.component.ts#L63)):*
> ```XML
> 
>     if (
>       this.electronService.isElectron &&
> ```

I've been curious about this check... when is isElectron ever not true? in unit / end to end tests or something?
___
*[`gui-js/libs/ui-components/src/lib/ravel-widget-view/ravel-widget-view.component.ts` line 123 at r1](https://reviewable.io/reviews/highperformancecoder/minsky/322#-NGmCkJf91E_Drgp-1UE:-NGmCkJf91E_Drgp-1UF:bb8nr2q) ([raw file](https://github.com/highperformancecoder/minsky/blob/888248890eb2c47623df611b7b3e62ae90df1a01/gui-js/libs/ui-components/src/lib/ravel-widget-view/ravel-widget-view.component.ts#L123)):*
> ```XML
>   
>    // eslint-disable-next-line @typescript-eslint/no-empty-function,@angular-eslint/no-empty-lifecycle-method
>   ngOnDestroy() {}
> ```

You can remove this along with the OnDestroy interface from the class declaration if you're not going to use destructor logic. Any of the lifecycle methods that start with "ng" are linked to the same interface with "ng" removed.

**Comment by highperformancecoder** [comment]
> I don't think calc(...) does anything here..? that's usually used to calculate a length based on two heterogenous values i.e. calc(100vh - 20px)


It doesn't look like it is needed. I'll try removing it.



> > ```
> >     this.render();
> >     this.initEvents();
> >     if (isMacOS()) this.yoffs=-20; // why, o why, Mac?
> > ```
> 
> If I recall correctly, the javascript mouse event has multiple subtly different X and Y values to choose from, which may include one that has a more homogenous value between different operating systems... it can also matter which HTML element you interept the mouse event on...
> 

Good point - but lets spin that out as a separate ticket. I was the one who added that kludge just to get things working for the 3.0 release. In retrospect, the different probably has to do with where each OS thinks the "hotpoint" is in a cursor. I vaguely recall Macs do something rather different to all other OSes.


> > ```
> 
> You can remove this along with the OnDestroy interface from the class declaration if you're not going to use destructor logic. Any of the lifecycle methods that start with "ng" are linked to the same interface with "ng" removed.

Does the OnDestroy interface do anything, or is it just syntactic sugar? Is it sufficient to have an ngDestroy() method when I need to do something at destruction?

**Comment by Rdmkr** [comment]
Does the OnDestroy interface do anything, or is it just syntactic sugar? Is
it sufficient to have an ngDestroy() method when I need to do something at
destruction?

— I'm fairly certain the intefaces do something and are necessary...
contrary to typescript as a language, the angular framework assigns
material importance to things like interfaces and object types... this is
among other things how it is able to resolve dependencies in the
constructors of components; that type info may not be there at runtime, but
it is there when angular handles the componenf lifecycle, and angular can
be quite finicky about what you present to it.

**Comment by highperformancecoder** [comment]
*[`gui-js/libs/ui-components/src/lib/ravel-widget-view/ravel-widget-view.component.ts` line 63 at r1](https://reviewable.io/reviews/highperformancecoder/minsky/322#-NGmCACF2mm9ON5tN4Ac:-NGtYjz23168uxFtwvTH:bmuswns) ([raw file](https://github.com/highperformancecoder/minsky/blob/888248890eb2c47623df611b7b3e62ae90df1a01/gui-js/libs/ui-components/src/lib/ravel-widget-view/ravel-widget-view.component.ts#L63)):*
<details><summary><i>Previously, Rdmkr wrote…</i></summary><blockquote>

I've been curious about this check... when is isElectron ever not true? in unit / end to end tests or something?
</blockquote></details>

No idea why this was added. Yes, the only time it is not true will be in unit tests.

**Review by Rdmkr — COMMENTED** [review]
> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/highperformancecoder/minsky/322)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @highperformancecoder)

**Review by highperformancecoder — COMMENTED** [review]
I just tried removing the OnDestroy interface and ngOnDestroy method on just this file alone, and it resulted in the application hanging on startup, so clearly Angular is quite finicky about this being there.
 

> *[Reviewable](https://reviewable.io/reviews/highperformancecoder/minsky/322#-:-NH1_e-iCP8LMAvbCelA:b-q8a3op)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @highperformancecoder)

**Comment by Rdmkr** [comment]
It's very strange that removing OnDestroy causes problems; certainly not normal Angular behavior. The only way I could explain that is if it's specific to Electron or something defined in our own system. Anyway, it can also not hurt to leave it there.

**Pull request merged**
