### PR TITLE
Group icon was not resizing properly on zoom in and out. Committing a…

### PR DESCRIPTION
**Pull request by wdednam**
… proposed fix.

---
This change is [Reviewable](https://reviewable.io/reviews/highperformancecoder/minsky/137)

### CODE REVIEW

**Comment by highperformancecoder** [comment]
This is effectively reverting a change I made. I don't understand how it even compiles, as now the "width" and "height" members are functions, not member variables.

The change I made width => iconWidth etc was out of an abundance of caution - the actual bug I was chasing was due to something else.

**Comment by wdednam** [comment]
It is a pity the commit comparison doesn't show a few lines of code around the changes:

In particular, the following line (775 in group.cc) which I guess you added to improve readability of Group::draw(), clarifies the situation:

unsigned width=z*this->iconWidth, height=z*this->iconHeight;

The changes I made were essentially just a correction of a few typos, not a regression to the previous width() or height() members. Sorry I didn't include a reference to the above line in my commit.

**Comment by highperformancecoder** [comment]
In that case I apologise. I was mislead by the way the code review tool presented the difference.

**Comment by wdednam** [comment]
Thanks, but there's no need to :). I will resolve to explain my commits a little better from now on.

 I didn't want raise another ticket at sourceforge for this because the tickets are already ballooning and I thought this was a quick fix we could do under the radar. I'm still struggling a bit with ticket 1072, to access the colWidgets vectors in TCL. I need to add getters because colWidgets and rowWidgets  are protected members of the godleyTableWindow class.

**Comment by highperformancecoder** [comment]
On Sat, Feb 01, 2020 at 02:17:35AM -0800, Wynand wrote:
> Thanks, but there's no need to :). I will resolve to explain my commits a
> little better from now on.

Usually, there is no need to. I can always ask questions!

Cheers


-- 

----------------------------------------------------------------------------
Dr Russell Standish                    Phone 0425 253119 (mobile)
Principal, High Performance Coders     hpcoder@hpcoders.com.au
                      http://www.hpcoders.com.au
----------------------------------------------------------------------------

**Pull request merged**
