### PR TITLE
Feature 165 publication tab

### PR DESCRIPTION
**Pull request by highperformancecoder**
This change is [Reviewable](https://reviewable.io/reviews/highperformancecoder/minsky/404)

### CODE REVIEW

**Review by Rdmkr — CHANGES_REQUESTED** [review]
> Reviewed 85 of 85 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/highperformancecoder/minsky/404)* status: all files reviewed, 2 unresolved discussions (waiting on @highperformancecoder)

___
*[`examples/1Free.mky` line 813 at r1](https://reviewable.io/reviews/highperformancecoder/minsky/404#-Nm0vlcC3MYZKBngs0r5:-Nm0vlcC3MYZKBngs0r6:b-egvs4w) ([raw file](https://github.com/highperformancecoder/minsky/blob/7d5b80e4c04066d897a5db3e939a56e67c2936ce/examples/1Free.mky#L813)):*
> ```
>    </flows>
>   </phillipsDiagram>
>   <publicationTabs>
> ```

Is this backwards compatible with mky files without this xml section?
___
*[`gui-js/libs/shared/src/lib/backend/minsky.ts` line 6 at r1](https://reviewable.io/reviews/highperformancecoder/minsky/404#-Nm0vGEp7w1D8AH74l3e:-Nm0vGEq6QzHlFqUxweK:b-n6k5pt) ([raw file](https://github.com/highperformancecoder/minsky/blob/7d5b80e4c04066d897a5db3e939a56e67c2936ce/gui-js/libs/shared/src/lib/backend/minsky.ts#L6)):*
> ```XML
> */
> 
> import {CppClass, Sequence, Container, Map, Pair} from './backend';
> ```

Is it supposed to happen that minsky.ts is being committed, while it was not part of the committed code base before?

**Review by highperformancecoder — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/highperformancecoder/minsky/404)* status: all files reviewed, 2 unresolved discussions (waiting on @Rdmkr)

___
*[`examples/1Free.mky` line 813 at r1](https://reviewable.io/reviews/highperformancecoder/minsky/404#-Nm0vlcC3MYZKBngs0r5:-Nm2x6gO6piEqceb8iaF:b-tskvqk) ([raw file](https://github.com/highperformancecoder/minsky/blob/7d5b80e4c04066d897a5db3e939a56e67c2936ce/examples/1Free.mky#L813)):*
<details><summary><i>Previously, Rdmkr wrote…</i></summary><blockquote>

Is this backwards compatible with mky files without this xml section?
</blockquote></details>

Yes - if that section is not present, an empty vector is loaded, so in practice it is optional. It won't be conformant with the schema, but that doesn't matter.

**Review by highperformancecoder — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/highperformancecoder/minsky/404)* status: all files reviewed, 2 unresolved discussions (waiting on @Rdmkr)

___
*[`gui-js/libs/shared/src/lib/backend/minsky.ts` line 6 at r1](https://reviewable.io/reviews/highperformancecoder/minsky/404#-Nm0vGEp7w1D8AH74l3e:-Nm2yZ-n0GMpp3kIPQuB:bl6mjsq) ([raw file](https://github.com/highperformancecoder/minsky/blob/7d5b80e4c04066d897a5db3e939a56e67c2936ce/gui-js/libs/shared/src/lib/backend/minsky.ts#L6)):*
<details><summary><i>Previously, Rdmkr wrote…</i></summary><blockquote>

Is it supposed to happen that minsky.ts is being committed, while it was not part of the committed code base before?
</blockquote></details>

I think we had this discussion before. There are reasons for including built files in the repo - in this case this allows someone who is only interested in making typescript changes make edits without having the full C++ development environment.

Similar reasons are behind including the documentation files, and assorted icon files that are "built".

**Comment by Rdmkr** [comment]
> > _[Reviewable](https://reviewable.io/reviews/highperformancecoder/minsky/404)_ status: all files reviewed, 2 unresolved discussions (waiting on @Rdmkr)
> 
> _[`gui-js/libs/shared/src/lib/backend/minsky.ts` line 6 at r1](https://reviewable.io/reviews/highperformancecoder/minsky/404#-Nm0vGEp7w1D8AH74l3e:-Nm2yZ-n0GMpp3kIPQuB:bl6mjsq) ([raw file](https://github.com/highperformancecoder/minsky/blob/7d5b80e4c04066d897a5db3e939a56e67c2936ce/gui-js/libs/shared/src/lib/backend/minsky.ts#L6)):_
> Previously, Rdmkr wrote…
> 
> I think we had this discussion before. There are reasons for including built files in the repo - in this case this allows someone who is only interested in making typescript changes make edits without having the full C++ development environment.
> 
> Similar reasons are behind including the documentation files, and assorted icon files that are "built".

sure, but these changes show up as newly appearing, not altering existing lines to me. That's what I'm curious about.

**Comment by highperformancecoder** [comment]
> > > _[Reviewable](https://reviewable.io/reviews/highperformancecoder/minsky/404)_ status: all files reviewed, 2 unresolved discussions (waiting on @Rdmkr)
> > 
> > 
> > _[`gui-js/libs/shared/src/lib/backend/minsky.ts` line 6 at r1](https://reviewable.io/reviews/highperformancecoder/minsky/404#-Nm0vGEp7w1D8AH74l3e:-Nm2yZ-n0GMpp3kIPQuB:bl6mjsq) ([raw file](https://github.com/highperformancecoder/minsky/blob/7d5b80e4c04066d897a5db3e939a56e67c2936ce/gui-js/libs/shared/src/lib/backend/minsky.ts#L6)):_
> > Previously, Rdmkr wrote…
> > I think we had this discussion before. There are reasons for including built files in the repo - in this case this allows someone who is only interested in making typescript changes make edits without having the full C++ development environment.
> > Similar reasons are behind including the documentation files, and assorted icon files that are "built".
> 
> sure, but these changes show up as newly appearing, not altering existing lines to me. That's what I'm curious about.

Well they aren't new commits in this PR. The code reviewer tool must've made a mistake.

**Review by Rdmkr — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/highperformancecoder/minsky/404#-:-Nm3d4QS-_vCsr66VmfT:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @highperformancecoder)

**Review by Rdmkr — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/highperformancecoder/minsky/404)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @highperformancecoder)

**Pull request merged**
